apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector: # same as ".spec.template.metadata.labels"
    matchLabels:
      app: nginx
  replicas: 2
  template: # Template describes pods that will be created.
    metadata:
      labels: # same as ".spec.selector"
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  # type: "ClusterIP" # means a service will only be accessible inside the cluster, via the cluster IP.
  # type: "ExternalName" # means a service consists of only a reference to an external name that kubedns or equivalent will return as a CNAME record, with no exposing or proxying of any pods involved.
  # type: "LoadBalancer" # means a service will be exposed via an external load balancer (if the cloud provider supports it), in addition to 'NodePort' type.
  type: "NodePort" # means a service will be exposed on one port of every node, in addition to 'ClusterIP' type.
  ports:
    - port: 8080 # The port that will be exposed by service.
      targetPort: 80 # Number or name of the port to access on the pods targeted by the service. Number must be in the range 1 to 65535.
      nodePort: 30080 # The port on each node on which this service is exposed when type is NodePort or LoadBalancer.
      protocol: TCP
  # Route service traffic to pods with label keys and values matching this selector.
  # If empty or not present, the service is assumed to have an external process managing its endpoints, which Kubernetes will not modify.
  # Only applies to types ClusterIP, NodePort, and LoadBalancer. Ignored if type is ExternalName.
  # More info: https://kubernetes.io/docs/concepts/services-networking/service/
  selector:
    app: nginx
