apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: ClusterIP
  selector:
    app: flask
  ports:
    - name: 80-tcp
      port: 4000
      protocol: TCP
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flask
        role: backend
    spec:
      containers:
        - image: app:latest
          imagePullPolicy: IfNotPresent
          name: app-container
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
      restartPolicy: Always
